#!/bin/bash

# Quick deployment script for VPK prototypes
# Deploys the latest code to production with automatic authentication handling
# 
# Usage:
#   pnpm deploy                     # Auto-generate version and deploy
#   pnpm deploy 1.0.100             # Deploy with specific version
#   pnpm deploy 1.0.100 skip        # Build & deploy without Docker push (uses fallback)
#
# Prerequisites:
#   - .deploy.local config file (generated by /vpk-deploy skill)
#   - Docker Desktop running
#   - atlas CLI installed and authenticated
#   - service-descriptor.yml configured
#
# This script automatically handles Docker registry authentication by:
# 1. Granting push permissions via atlas packages permission grant
# 2. Logging into Docker registry with credentials from .deploy.local
# 3. Building and pushing the image
# 4. Deploying to Micros

set -e

# Load configuration from .deploy.local
CONFIG_FILE=".deploy.local"
if [ ! -f "$CONFIG_FILE" ]; then
  echo "❌ Missing .deploy.local config file"
  echo ""
  echo "This file is generated during your first deployment."
  echo "Run /vpk-deploy to set up deployment configuration."
  echo ""
  exit 1
fi

# Source the config file to load SERVICE_NAME, DOCKER_USERNAME, DOCKER_PASSWORD, ENV
source "$CONFIG_FILE"

# Validate required variables from config
if [ -z "$SERVICE_NAME" ] || [ -z "$DOCKER_USERNAME" ] || [ -z "$DOCKER_PASSWORD" ]; then
  echo "❌ Invalid .deploy.local config"
  echo ""
  echo "Required variables: SERVICE_NAME, DOCKER_USERNAME, DOCKER_PASSWORD"
  echo "Run /vpk-deploy to regenerate the config file."
  echo ""
  exit 1
fi

VERSION="${1:-1.0.$(date +%s | tail -c 4)}"  # Auto-generate version from timestamp if not provided
ENV="${ENV:-pdev-west2}"  # Use ENV from config or default to pdev-west2
SKIP_PUSH="${2:-}"
REGISTRY="docker.atl-paas.net"

# Color codes for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Helper functions
print_header() {
  echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
  echo -e "${BLUE}$1${NC}"
  echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
}

print_step() {
  echo ""
  echo -e "${BLUE}📍 $1${NC}"
}

print_success() {
  echo -e "${GREEN}✅ $1${NC}"
}

print_error() {
  echo -e "${RED}❌ $1${NC}"
}

print_warning() {
  echo -e "${YELLOW}⚠️  $1${NC}"
}

# Pre-flight checks
print_header "🚀 Pre-Flight Checks"

# Check Docker daemon
print_step "Checking Docker daemon..."
if ! docker info > /dev/null 2>&1; then
  print_error "Docker daemon not running. Please start Docker Desktop."
  exit 1
fi
print_success "Docker daemon is running"

# Check atlas CLI
print_step "Checking atlas CLI..."
if ! command -v atlas &> /dev/null; then
  print_error "atlas CLI not found. Please install it first."
  exit 1
fi
print_success "atlas CLI is installed"

# Setup Docker authentication (only if not skipping push)
if [ "$SKIP_PUSH" != "skip" ]; then
  print_step "Setting up Docker authentication..."
  
  # Step 1: Grant push permissions via atlas
  echo "  → Granting push permissions..."
  if atlas packages permission grant > /dev/null 2>&1; then
    print_success "Push permissions granted"
  else
    print_warning "Could not grant permissions (may already be granted)"
  fi
  
  # Step 2: Login to Docker registry with embedded credentials
  echo "  → Logging into Docker registry..."
  echo "$DOCKER_PASSWORD" | docker login "$REGISTRY" --username "$DOCKER_USERNAME" --password-stdin > /dev/null 2>&1
  if [ $? -eq 0 ]; then
    print_success "Docker authentication successful"
  else
    print_error "Docker login failed"
    exit 1
  fi
fi

# Deployment
print_header "🚀 Deploying $SERVICE_NAME version $VERSION to $ENV"

# Step 1: Build Docker image
print_step "Step 1/3: Building Docker image..."
if docker buildx build --platform linux/amd64 --no-cache \
  -t $REGISTRY/${SERVICE_NAME}:app-${VERSION} \
  -f backend/Dockerfile . --load; then
  print_success "Docker image built successfully"
else
  print_error "Docker build failed"
  exit 1
fi

# Step 2: Push to registry
if [ "$SKIP_PUSH" = "skip" ]; then
  print_step "Step 2/3: Skipping Docker push (as requested)"
  print_warning "Will deploy with existing image version"
else
  print_step "Step 2/3: Pushing Docker image to registry..."
  if docker push $REGISTRY/${SERVICE_NAME}:app-${VERSION}; then
    print_success "Docker image pushed successfully"
  else
    print_error "Docker push failed"
    echo ""
    echo "Troubleshooting tips:"
    echo "  1. Check if API token is still valid at https://packages.atlassian.com/"
    echo "  2. Try running: atlas packages permission grant"
    echo "  3. Try manual login: docker logout $REGISTRY && docker login $REGISTRY"
    echo ""
    exit 1
  fi
fi

# Step 3: Deploy to Micros
print_step "Step 3/3: Deploying to Micros..."
export VERSION=$VERSION
if atlas micros service deploy \
  --service=$SERVICE_NAME \
  --env=$ENV \
  --file=service-descriptor.yml; then
  print_success "Deployment initiated successfully"
else
  print_error "Deployment failed"
  exit 1
fi

# Summary
print_header "✨ Deployment Complete!"

echo ""
echo -e "${GREEN}📍 Service URL:${NC}"
echo "  https://$SERVICE_NAME.us-west-2.platdev.atl-paas.net"
echo ""
echo -e "${GREEN}🔍 Monitor deployment:${NC}"
echo "  atlas micros service show --service=$SERVICE_NAME --env=$ENV"
echo ""
echo -e "${GREEN}🏥 Health check:${NC}"
echo "  curl https://$SERVICE_NAME.us-west-2.platdev.atl-paas.net/api/health"
echo ""
echo -e "${GREEN}📊 View logs:${NC}"
echo "  https://go.atlassian.com/logs/$ENV/$SERVICE_NAME"
echo ""
echo -e "${GREEN}🎯 Deployed version: $VERSION${NC}"
echo ""

print_success "All done! Your service should be live in ~30 seconds"
echo ""
